# Generated by Django 5.1.1 on 2025-03-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('batting_type', models.CharField(max_length=50)),
                ('bowling_type', models.CharField(max_length=50)),
                ('jersey', models.IntegerField()),
            ],
        ),
    ]
