# Generated by Django 5.1.1 on 2025-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='../playerImage/default.png', upload_to='player_images/'),
            preserve_default=False,
        ),
    ]
