# Generated by Django 5.1.1 on 2025-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='jersey',
        ),
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(default='No Category', max_length=10),
            preserve_default=False,
        ),
    ]
