# Generated by Django 5.1.7 on 2025-04-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_jersey_player_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D')], default='', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.category'),
        ),
    ]
