# Generated by Django 5.1.7 on 2025-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_batting_type_alter_player_bowling_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_type',
            field=models.CharField(choices=[('right-bat', 'Right Arm Batsman'), ('left-bat', 'Left Arm Batsman')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_type',
            field=models.CharField(choices=[('none', 'None'), ('right-fast', 'Right Arm Fast'), ('left-fast', 'Left Arm Fast'), ('right-mid', 'Right Arm Medium'), ('left-mid', 'Left Arm Medium'), ('right-off-spin', 'Right Arm Off Spin'), ('left-off-spin', 'Left Arm Off Spin'), ('right-lef-spin', 'Right Arm Leg Spin'), ('left-leg-spin', 'Left Arm Leg Spin')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('bat', 'Batsman'), ('bowl', 'Bowler'), ('bat-all', 'Batting All-rounder'), ('bowl-all', 'Bowling All-rounder')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('pak', 'Pakistan'), ('ban', 'Bangladesh')], default='', max_length=100),
        ),
    ]
