# Generated by Django 5.1.7 on 2025-04-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_player_batting_type_alter_player_bowling_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('Pakistan', 'Pakistan'), ('Bangladesh', 'Bangladesh')], default='', max_length=100),
        ),
    ]
