# Generated by Django 5.1.7 on 2025-04-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='', max_length=5),
        ),
    ]
