# Generated by Django 5.1.7 on 2025-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_team_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='country',
        ),
    ]
