# Generated by Django 5.1.7 on 2025-04-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_rename_team_player_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Wicket Keeper Batsman', 'Wicket Keeper Batsman'), ('Bowler', 'Bowler'), ('Batting All-rounder', 'Batting All-rounder'), ('Bowling All-rounder', 'Bowling All-rounder')], default='', max_length=100),
        ),
    ]
