# Generated by Django 5.1.7 on 2025-04-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='player-img/logo.png', upload_to='player_images/'),
        ),
    ]
