# Generated by Django 5.1.7 on 2025-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(default='player-img/logo.png', upload_to='player_images/')),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
