# Generated by Django 5.1.7 on 2025-04-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
