# Generated by Django 5.1.7 on 2025-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_team_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.IntegerField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], default=0, max_length=20),
        ),
    ]
